apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: MYNAME-dev
  namespace: MYNAME-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: MYNAME-dev
subjects:
- kind: ServiceAccount
  name: MYNAME-dev
  # namespace erklärt auf welches Namespace sich die RoleBinding beziehen soll
  namespace: MYNAME-dev
